export const AlbumList = [
{"id": 1,
    "album_name": "Nevermind",
    "artist_name": "Nirvana",
    "genre": "Rock",
    "year": 1991,
},
{"id": 2,
"album_name": "The Chronic",
"artist_name": "Dr. Dre",
"genre": "Hip-Hop",
"year": 1992,
},
{"id": 3,
"album_name": "Voodoo",
"artist_name": "D'Angelo",
"genre": "R&B/Soul",
"year": 2000,
},
{"id": 4,
"album_name": "Bitches Brew",
"artist_name": "Miles Davis",
"genre": "Jazz",
"year": 1970,
},
{"id": 5,
"album_name": "Revolver",
"artist_name": "The Beatles",
"genre": "Pop",
"year": 1966,
},
{"id": 6,
"album_name": "Vespertine",
"artist_name": "Björk",
"genre": "Art Pop",
"year": 2001,
},
{"id": 7,
"album_name": "Amazing Grace",
"artist_name": "Aretha Franklin",
"genre": "Gospel",
"year": 1972,
},
{"id": 8,
"album_name": "Kid A",
"artist_name": "Radiohead",
"genre": "Art Rock",
"year": 2000,
},
{"id": 9,
"album_name": "Graceland",
"artist_name": "Paul Simon",
"genre": "Pop",
"year": 1986,
},
{"id": 10,
"album_name": "Grace",
"artist_name": "Jeff Buckley",
"genre": "Rock",
"year": 1994,
},
]